baseURL = "https://pawelgrzybek.com"
title = "pawelgrzybek.com"
disableKinds = ["section", "taxonomy", "term"]
pygmentsUseClasses = true
enableRobotsTXT = true

[params]
  description = "I'm Pawel Grzybek, a Software Engineer from Poland. I build Web stuff and write about it. A keen cyclist and a funky/jazz records collector. Welcome to my website!"

[frontmatter]
  date  = [":filename", ":default"]

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  baseName = "feed"

[outputFormats.JSON]
  baseName = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
