baseURL = "https://pawelgrzybek.com/"
title = "pawelgrzybek.com"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
disqusShortname = "studiorgb"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Hi there, I'm Pawel Grzybek, Front-end Developer from Poland. Nowadays I live in Leicester (UK). When I'm not coding, I'm spinning funky vinyl records."

[frontmatter]
  date  = [":filename", ":default"]

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"
